version: '3'
services:
  init_db:
    image: governmentpaas/psql:latest
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      TSD_DB: "${TSD_DB}"
      TSD_DB_USER: "${TSD_DB_USER}"
      TSD_DB_PASSWORD: "${TSD_DB_PASSWORD}"
      DATAREP_DB: "${DATAREP_DB}"
      DATAREP_DB_USER: "${DATAREP_DB_USER}"
      DATAREP_DB_PASSWORD: "${DATAREP_DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGPASSWORD: "${DB_PASSWORD}"
    tty: true
    working_dir: /
    command: ["/bin/sh", "/scripts/initdb.sh"]
    volumes:
      - ./scripts:/scripts
      - ./docker/timescale/sql:/sql_create
      - ./tsdsystem/docker/timescale/sql:/sql_tsd
    deploy:
      placement:
        constraints:
          - "node.labels.tier == frontend"
      replicas: 1
      restart_policy:
        condition: none
  init_invenio:
    image: ${REGISTRY_URL}/oedatarep-invenio-rdm
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['es:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${DATAREP_DB_USER}:${DATAREP_DB_PASSWORD}@db/${DATAREP_DB}"
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
      - "IRDM_ADMIN_USER=${IRDM_ADMIN_USER}"
      - "IRDM_ADMIN_PASSWORD=${IRDM_ADMIN_PASSWORD}"
    tty: true
    working_dir: /
    command: ["/bin/sh", "/scripts/initinvenio.sh"]
    volumes:
      - ./scripts:/scripts
    deploy:
      placement:
        constraints:
          - "node.labels.tier == frontend"
      replicas: 1
      restart_policy:
        condition: none
