networks:
  public_net:
    external: true
    name: oedatarep-public
  default:
    driver: overlay

services:
  db:
    image: postgres:14.13
    networks:
      - default
    deploy:
      placement:
        constraints:
          - "node.labels.tier == backend"
    environment:
      - "POSTGRES_USER=${DATAREP_DB_USER}"
      - "POSTGRES_PASSWORD=${DATAREP_DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis
    #read_only: true
    networks:
      - default
    deploy:
      placement:
        constraints:
          - "node.labels.tier == backend"

  mq:
    image: rabbitmq:3.8-management
    networks:
      - default
    deploy:
      placement:
        constraints:
          - "node.labels.tier == backend"

  search:
    image: opensearchproject/opensearch:2.3.0
    networks:
      - default
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 2G
      placement:
        constraints:
          - "node.labels.tier == backend"
    volumes:
      - os_data:/usr/share/elasticsearch/data

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.3.0
    networks:
      - default
    environment:
      - 'OPENSEARCH_HOSTS=["http://search:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == frontend"

  pgadmin:
    image: dpage/pgadmin4:5.2
    networks:
      - default
    ports:
      - "5059:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == backend"

  # UI Application
  web-ui:
    image: oedatarep-invenio-rdm:${IMAGE_TAG}
    networks:
      public_net:
        aliases:
          - web-ui_service
      default:
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['search:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      # Nota: qui db risolve al postgres locale di questo stack
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${DATAREP_DB_USER}:${DATAREP_DB_PASSWORD}@db/${DATAREP_DB}"
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
      # Se serve contattare TSD:
      # - "TSD_API_URL=http://tsd_service:80"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == frontend"
    command: ["uwsgi /opt/invenio/var/instance/uwsgi_ui.ini"]
    volumes:
      - ./oedatarep-invenio-rdm/invenio.cfg:/opt/invenio/var/instance/invenio.cfg
      - static_data:/opt/invenio/var/instance/static
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive

  # API Rest Application
  web-api:
    image: oedatarep-invenio-rdm:${IMAGE_TAG}
    networks:
      public_net:
        aliases:
          - web-api_service
      default:
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['search:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${DATAREP_DB_USER}:${DATAREP_DB_PASSWORD}@db/${DATAREP_DB}"
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == frontend"
    command: ["uwsgi /opt/invenio/var/instance/uwsgi_rest.ini"]
    volumes:
      - ./oedatarep-invenio-rdm/invenio.cfg:/opt/invenio/var/instance/invenio.cfg
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive

  # Worker
  worker:
    image: oedatarep-invenio-rdm:${IMAGE_TAG}
    restart: "unless-stopped"
    networks:
      - default
      - public_net # Connesso alla pubblica se deve parlare con TSD
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['search:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${DATAREP_DB_USER}:${DATAREP_DB_PASSWORD}@db/${DATAREP_DB}"
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == frontend"
    command: ["celery -A invenio_app.celery worker -B --loglevel=INFO"]
    volumes:
      - ./oedatarep-invenio-rdm/invenio.cfg:/opt/invenio/var/instance/invenio.cfg
      - uploaded_data:/opt/invenio/var/instance/data
    depends_on:
      - "search"
      - "cache"
      - "db"
      - "mq"
    extra_hosts:
      - "sandbox-datarep-fe.ct.int.ingv.it:172.22.122.100"
  init_invenio:
      image: ${REGISTRY_URL}/oedatarep-invenio-rdm:${IMAGE_TAG}
      deploy:
        replicas: 0  # <--- Spento di default
        restart_policy:
          condition: on-failure
        placement:
          constraints:
            - "node.labels.tier == frontend" # O dove preferisci
      networks:
        - default # Vede db, search, redis, mq di questo stack
      environment:
        - "POSTGRES_USER=${DATAREP_DB_USER}"
        - "POSTGRES_PASSWORD=${DATAREP_DB_PASSWORD}"
        - "PGPASSWORD=${DATAREP_DB_PASSWORD}"
        - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
        - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
        - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
        - "INVENIO_CACHE_TYPE=redis"
        - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
        - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
        - "INVENIO_SEARCH_ELASTIC_HOSTS=['es:9200']"
        - "INVENIO_SECRET_KEY=CHANGE_ME"
        - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${DATAREP_DB_USER}:${DATAREP_DB_PASSWORD}@db/${DATAREP_DB}"
        - "INVENIO_WSGI_PROXIES=2"
        - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
        - "IRDM_ADMIN_USER=${IRDM_ADMIN_USER}"
        - "IRDM_ADMIN_PASSWORD=${IRDM_ADMIN_PASSWORD}"
      tty: true
      working_dir: /
      command: >
        /bin/sh -c "
        dnf install -y postgresql &&
        /bin/sh /scripts/initinvenio.sh
        "
      volumes:
        - ./scripts:/scripts
        - ./oedatarep-invenio-rdm/invenio.cfg:/opt/invenio/var/instance/invenio.cfg

volumes:
  postgres_data:
  os_data:
  static_data:
    external: true
    name: datarep_static_data
  uploaded_data:
  archived_data:
