# Example of a full infrastructure stack
#
# Note, this file is not suitable for a production deployment. It is only an
# example of all the infrastructure components needed in a real production
# deployment.
#
# Usage::
#
#   $ docker-compose up -f docker-compose.full.yml -d
#
# Following services are included:
# - Frontend: Nginx (exposed ports: 40 and 443)
# - UI application: UWSGI (not exposed)
# - API application: UWSGI (not exposed)
# - Cache: Redis (exposed port: 6379)
# - DB: (PostgresSQL/MySQL) (exposed port: 5432 or 3306)
# - Message queue: RabbitMQ (exposed ports: 5672, 15672)
# - Elasticsearch (exposed ports: 9200, 9300)
# - Kibana (view ES indexes) (exposed ports: 5601)
#
version: '3'
services:
  cache:
    image: redis
    restart: "unless-stopped"
    read_only: true
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == backend"
  db:
    image: timescale/timescaledb-ha:pg14.2-ts2.6.0-oss-latest
    restart: "unless-stopped"
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == backend"
    volumes:
      - postgres_data:/home/postgres/pgdata/data
  mq:
    image: rabbitmq:3.8-management
    restart: "unless-stopped"
    ports:
      - "15672:15672"
      - "5672:5672"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == backend"
  search:
    image: opensearchproject/opensearch:2.3.0
    restart: "unless-stopped"
    environment:
      # settings only for development. DO NOT use in production!
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    deploy:
      resources:
        limits:
          memory: 2G
      placement:
        constraints:
          - "node.labels.tier == backend"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.3.0
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      # settings only for development. DO NOT use in production!
      - 'OPENSEARCH_HOSTS=["http://search:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == frontend"
  pgadmin:
    image: dpage/pgadmin4:5.2
    restart: "unless-stopped"
    ports:
      - "5050:80"
      - "5051:443"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == backend"
  # Frontend
  frontend:
    build: ./docker/nginx/
    image: ${REGISTRY_URL}/oedatarep-invenio-rdm-frontend
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == frontend"
    volumes:
      - static_data:/opt/invenio/var/instance/static
    depends_on:
      - web-ui
      - web-api
  # UI Application
  web-ui:
    build:
      context: ./oedatarep-invenio-rdm
      args:
        - ENVIRONMENT=DEV
        - OEDATAREP_RELEASE=v0.2
    restart: "unless-stopped"
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['search:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${DATAREP_DB_USER}:${DATAREP_DB_PASSWORD}@db/${DATAREP_DB}"
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == frontend"
    command: ["uwsgi /opt/invenio/var/instance/uwsgi_ui.ini"]
    image: ${REGISTRY_URL}/oedatarep-invenio-rdm:latest
    ports:
      - "5000"
    volumes:
      - ./oedatarep-invenio-rdm/invenio.cfg:/opt/invenio/var/instance/invenio.cfg
      - static_data:/opt/invenio/var/instance/static
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive

  # API Rest Application
  web-api:
    build:
      context: ./oedatarep-invenio-rdm
      args:
        - ENVIRONMENT=DEV
        - OEDATAREP_RELEASE=v0.2
    image: ${REGISTRY_URL}/oedatarep-invenio-rdm
    restart: "unless-stopped"
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['search:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${DATAREP_DB_USER}:${DATAREP_DB_PASSWORD}@db/${DATAREP_DB}"
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == frontend"
    command: ["uwsgi /opt/invenio/var/instance/uwsgi_rest.ini"]
    ports:
      - "5000"
    volumes:
      - ./oedatarep-invenio-rdm/invenio.cfg:/opt/invenio/var/instance/invenio.cfg
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive

  # Worker
  worker:
    build:
      context: ./oedatarep-invenio-rdm
      args:
        - ENVIRONMENT=DEV
        - OEDATAREP_RELEASE=v0.2
    image: ${REGISTRY_URL}/oedatarep-invenio-rdm
    restart: "unless-stopped"
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['search:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${DATAREP_DB_USER}:${DATAREP_DB_PASSWORD}@db/${DATAREP_DB}"
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
    deploy:
      placement:
        constraints:
          - "node.labels.tier == frontend"
    command: ["celery -A invenio_app.celery worker -B --loglevel=INFO"]
    volumes:
      - ./oedatarep-invenio-rdm/invenio.cfg:/opt/invenio/var/instance/invenio.cfg
      - uploaded_data:/opt/invenio/var/instance/data
    depends_on:
      - "es"
      - "cache"
      - "db"
      - "mq"
    extra_hosts:
      - "oedatarep.ct.ingv.it:192.168.100.10"
  # TSD_APP_FE
  tsd_app:
    build:
      context: tsdsystem/docker/php/
    image: ${REGISTRY_URL}/tsd
    tty: true
    depends_on:
      - db
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${TSD_DB_USER}"
      DB_PASSWORD: "${TSD_DB_PASSWORD}"
      DB_NAME: "${TSD_DB}"
      SERVER_KEY: "${SERVER_KEY}"
      APP_ALLOWED_HOSTS: "${APP_ALLOWED_HOSTS}"
      ADMIN_ID: "${ADMIN_ID}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
    ports:
      - "8000:80"
    working_dir: /var/www/html/tsdws
    deploy:
      placement:
        constraints:
          - "node.labels.tier == frontend"
    volumes:
      - ./tsdsystem/src:/var/www/html
volumes:
  static_data:
  uploaded_data:
  archived_data:
  postgres_data:
  es_data:
