version: '2.2'
services:
  init_db:
    image: governmentpaas/psql:latest #timescale/timescaledb-ha:pg14.2-ts2.6.0-oss-latest
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      TSD_DB: "${TSD_DB}"
      TSD_DB_USER: "${TSD_DB_USER}"
      TSD_DB_PASSWORD: "${TSD_DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGPASSWORD: "${DB_PASSWORD}"
    tty: true
    working_dir: /
    command: ["/bin/sh", "/scripts/initdb.sh"]
    volumes:
      - ./scripts:/scripts
      - ./docker/timescale/sql:/sql_create
      - ./tsdsystem/docker/timescale/sql:/sql_tsd
networks:
  default:
    name: datarep_net
    external: true