networks:
  public_net:
    external: true
    name: oedatarep-public
  default:
    driver: overlay

services:
  tsd:
    build:
      context: tsdsystem/docker/php/
    image: tsd
    tty: true
    networks:
      public_net:
        aliases:
          - tsd_service  # Alias DNS per Nginx e DATAREP stack
      default:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.tier == frontend"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${TSD_DB_USER}"
      DB_PASSWORD: "${TSD_DB_PASSWORD}"
      DB_NAME: "${TSD_DB}"
      SERVER_KEY: "${SERVER_KEY}"
      APP_ALLOWED_HOSTS: "${APP_ALLOWED_HOSTS}"
      ADMIN_ID: "${ADMIN_ID}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
    depends_on:
      - db
    working_dir: /var/www/html/tsdws
    volumes:
      - ./tsdsystem/src:/var/www/html

  pgadmin:
    image: dpage/pgadmin4:5.2
    restart: "unless-stopped"
    ports:
      - "5050:80"
      - "5051:443"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    deploy:
      replicas: 0
      placement:
        constraints:
          - "node.labels.tier == backend"

  db:
    image: timescale/timescaledb-ha:pg14.2-ts2.6.0-oss-latest
    restart: "unless-stopped"
    networks:
      - default
    deploy:
      placement:
        constraints:
          - "node.labels.tier == backend"
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "5432"
    volumes:
      - postgres_data:/home/postgres/pgdata/data

volumes:
  postgres_data:
