-- Role: DATAREP_DB_USER
-- DROP ROLE DATAREP_DB_USER;

CREATE ROLE "DATAREP_DB_USER" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'DATAREP_DB_PASSWORD';
  