-- Database: tsdsystem

-- DROP DATABASE tsdsystem;

CREATE DATABASE tsdsystem
    WITH 
    OWNER = tsdsystem
    ENCODING = 'UTF8'
    LC_COLLATE = 'C.UTF-8'
    LC_CTYPE = 'C.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

\connect tsdsystem;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO tsdsystem WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO superuser;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON SEQUENCES TO tsdsystem WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON SEQUENCES TO superuser;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO tsdsystem WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO superuser;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO PUBLIC;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO tsdsystem;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO superuser;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO PUBLIC;
