-- Database: DATAREP_DB

-- DROP DATABASE "DATAREP_DB";

CREATE DATABASE "DATAREP_DB"
    OWNER "DATAREP_DB_USER"
    ENCODING 'UTF8'
    LC_COLLATE 'C.UTF-8'
    LC_CTYPE 'C.UTF-8'
    TABLESPACE pg_default
    CONNECTION LIMIT -1;

\connect "DATAREP_DB";

DROP EXTENSION  IF EXISTS timescaledb;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO "DATAREP_DB_USER" WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON SEQUENCES TO "DATAREP_DB_USER" WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO "DATAREP_DB_USER" WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO PUBLIC;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO "DATAREP_DB_USER";

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO PUBLIC;
