-- Database: oedatarep-invenio-rdm

-- DROP DATABASE "oedatarep-invenio-rdm";

CREATE DATABASE "oedatarep-invenio-rdm"
    OWNER "oedatarep-invenio-rdm"
    ENCODING 'UTF8'
    LC_COLLATE 'C.UTF-8'
    LC_CTYPE 'C.UTF-8'
    TABLESPACE pg_default
    CONNECTION LIMIT -1;

\connect "oedatarep-invenio-rdm";

DROP EXTENSION  IF EXISTS timescaledb;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO "oedatarep-invenio-rdm" WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON SEQUENCES TO "oedatarep-invenio-rdm" WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO "oedatarep-invenio-rdm" WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO PUBLIC;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO "oedatarep-invenio-rdm";

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO PUBLIC;
