-- Role: tsdsystem
-- DROP ROLE tsdsystem;

CREATE ROLE tsdsystem WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  CREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:FGX7iPTcefAGyVjM+TFYMA==$3zHuG+vFiH4oHSjTAK9K69muTmWxdiB1Dt5rhQnLj4M=:9y9jgbyC89I23E+FUBKvmHR0QtNCThod1VUbaewDD2w=';
