CREATE ROLE "oedatarep-invenio-rdm" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:LfSyolawCAbHTW/xWj2OlQ==$2c8lsT1vlOuKRptziqdmO+0a1KYoJVeCAes2slVmbhc=:CDgALKcBSHE+kzhV5I51rn2w3Y7ZnhNCXeniazcVw+Y=';
  