\connect tsdsystem;
CREATE EXTENSION IF NOT EXISTS postgis CASCADE;

CREATE SCHEMA IF NOT EXISTS tsd_pnet AUTHORIZATION tsdsystem;
CREATE SCHEMA IF NOT EXISTS tsd_main AUTHORIZATION tsdsystem;
CREATE SCHEMA IF NOT EXISTS tsd_users AUTHORIZATION tsdsystem;